name: Build Package

runs:
  using: composite

  steps:
    - uses: seanmiddleditch/gha-setup-ninja@master

    - uses: ilammy/msvc-dev-cmd@v1
      if: contains(matrix.cfg.ARCHITECTURE, '-x64-msvc143')
      with:
        arch: x64

    - uses: ilammy/msvc-dev-cmd@v1
      if: contains(matrix.cfg.ARCHITECTURE, '-arm64-msvc143')
      with:
        arch: amd64_arm64

    # TODO: Add Windows ARM64EC architecture

    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.32'

    - name: Install additional packages
      if: matrix.cfg.os == 'ubuntu-20.04'
      shell: bash
      run: sudo apt update && sudo apt install -y gcc-9 g++-9 gcc-9-arm-linux-gnueabihf g++-9-arm-linux-gnueabihf gcc-9-aarch64-linux-gnu g++-9-aarch64-linux-gnu clang-10

    - name: Install Python deps
      shell: bash
      run: |
        python3 -m venv ~/venv
        source ~/venv/bin/activate
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        [ -f packages/$PACKAGE/requirements.txt ] && python3 -m pip install -r packages/$PACKAGE/requirements.txt || true
        
    - uses: egor-tensin/setup-mingw@v2
      if: contains(matrix.cfg.triple, '-mingw64')
      with:
        static: 0
        platform: x64

    - name: Invoke Python build script
      shell: bash
      run: |
        TRIPLE=${{matrix.cfg.triple}} \
        python3 build.py $PACKAGE
  
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.6.1
      with:
        file: out/**.tar.gz
        file_glob: true
        tag: latest
        overwrite: true
