name: Build mbedtls

on:
  push:
    paths:
      - .github/actions/build-package/action.yaml
      - .github/workflows/build-mbedtls.yaml
      - packages/mbedtls/**
      - build.py
      - scripts/tools.py

jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}

    env:
      PACKAGE: mbedtls

    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-20.04, triple: linux-x64-clang10 }
          - { os: ubuntu-20.04, triple: linux-x64-gcc9 }
          - { os: ubuntu-20.04, triple: linux-armv7-gcc9 }
          - { os: ubuntu-20.04, triple: linux-aarch64-gcc9 }
          - { os: windows-2022, triple: windows-x64-msvc143 }
          - { os: windows-2022, triple: windows-arm64-msvc143 }
          - { os: windows-2022, triple: windows-x64-mingw64 }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build package
        uses: ./.github/actions/build-package

