name: Build freeimage

on:
  push:
    paths:
      - .github/actions/build-package/action.yaml
      - .github/workflows/build-freeimage.yaml
      - packages/freeimage/**
      - build.py
      - scripts/tools.py

jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}

    env:
      PACKAGE: freeimage

    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-20.04, triple: linux-x64-clang7 }
          - { os: ubuntu-20.04, triple: linux-x64-gcc7 }
          - { os: windows-2022, triple: windows-x64-mingw64 }
          - { os: windows-2022, triple: windows-x64-msvc }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build package
        uses: ./.github/actions/build-package

